# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

###############
# customized settings
###############
title: Zhaoting's Blog
email: wztwcy@gmail.com
ar: "zhaoting"
description: > # this means to ignore newlines until "baseurl:"
  This is Zhaoting's blog. I like python, linux and soccer! Welcome!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://magodo.github.io" # the base hostname & protocol for your site
twitter_username: magodo_
github_username: magodo

# post excerpt
excerpt_separator: <!--more-->

# front matter defaults
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#      type: "posts"
#    values:
#      layout: "post"
                

